var bingoValues = [
"Lacey Chabert"
, "Winnie Cooper"
,"Red-Haired Chick"
, "Single Parent"
, "Conveniently Dead Spouse"
, "Exile to Small Town America"
, "Name Brand Actor"
, 'You\'ve been "It\'s a Wonderful Life"d'
, "Heroine Owns the Business"
, "Job in Danger"
, "Save the Farm!"
, "Sassy BFF"
, "...Then, Santa Shows Up"
, "Childhood Dreams Come True"
, "Falling for the Enemy"
, "Groundhog Day"
, "Fancy Woman Packs Wrong"
, "Childhood Sweethearts Reconnect"
, "Christmas is Cancelled... But Wait!"
, "Scrooged!"
, "Car Breaks Down"
, "Must Save Public Space"
, "The Festival!"
, "Sing Us Something in the Public Domain"
, "Never Perform with Animals or Children"
, "Some Damn Kid Solves Everything"
, "Coffee!"
, "Heroine with a Dead Parent"
, "Bitchy GF or Asshole BF"
, "Exotic Vacation Cancelled"
, "Charity Work"
, "Blue collar/White Collar Star Crossed Love"]
