var bingoValues = [
"Lacey Chabert"
, "Winnie Cooper"
,"Red-Haired Chick"
, "Single Parent"
, "Conveniently Dead Spouse"
, "Exile to Small Town America"
, "Name Brand Actor"
, 'You\'ve been "It\'s a Wonderful Life"d'
, "Heroine Owns the Business"
, "Job in Danger"
, "Save the Farm!"
, "Sassy BFF"
, "DJ, from the Full House"
, "...Then, Santa Shows Up"
, "Childhood Dreams Come True"
, "Falling for the Enemy"
, "Groundhog Day"
, "Fancy Woman Packs Wrong"
, "Childhood Sweethearts Reconnect"
, "Christmas is Cancelled... But Wait!"
, "Scrooged!"
, "Car Breaks Down"
, "Must Save Public Space"
, "The Festival!"
, "Sing Us Something in the Public Domain"
, "Never Perform with Animals or Children"
, "Some Damn Kid Solves Everything"
, "Coffee!"
, "Heroine with a Dead Parent"
, "Bitchy GF or Asshole BF"
, "Exotic Vacation Cancelled"
, "Charity Work"
, "Blue collar/White Collar Star Crossed Love"
, "D-I-V-O-R-C-E"
, "Carcinogenic Snow"
, "Potemkin Village"
, "It's a Benetton Christmas"
, "They Paid the Rights!"
, "Spent All the Money on The Actors"
, "Sleigh Ride with Animal Cruelty"
, "Town Square Make Out"
, "Downton Abbey Staff Christmas"
, "\'Jesus? Is That The Guy at Nanay\'s House?\' "]
